defaults:
  - hydra: default
  - _self_

save_dir: "/home/mila/t/tom.marty/IFT6269/project/VariationalCausalModelling/logs"
seed: 1

logger:
  _target_: lightning.pytorch.loggers.WandbLogger
  entity: dhanya-shridar
  project: VariationalCM
  name: ${now:%Y-%m-%d}_${now:%H-%M-%S}
  save_dir: ${save_dir}
  offline: False
  tags: null

task :
  _target_: task.SCM_Reconstruction
  encoder: ${encoder}
  decoder: ${decoder}
  lr: 1e-4
  temperature: 0.5
  beta: 1.0
  is_beta_VAE : False

SCM:
  _target_: dataset.SCM
  n_variables : 10
  density : 0.4
  interventional_shift : 10.0

train_dataset:
  _target_: dataset.SCM_Dataset
  generator : LinearANM
  n_samples: 10000
  scm: ${SCM}
  observational_density: 0.1
  shift: 1.0

val_dataset:
  _target_: dataset.SCM_Dataset
  generator : ${train_dataset.generator}
  n_samples: 1000
  scm: ${SCM}
  observational_density: ${train_dataset.observational_density}
  shift: ${train_dataset.shift}

datamodule:
  _target_: dataset.SCMDataModule
  batch_size: 128
  train_dataset: ${train_dataset}
  val_dataset: ${val_dataset}

trainer:
  max_epochs: 100
  enable_progress_bar: True
  log_every_n_steps: 10
  val_check_interval: 1


encoder:
  _target_: model.CMEncoder
  input_dim: ${SCM.n_variables}
  hidden_dim: 64
  latent_dim: "${ast_eval:'${SCM.n_variables}+1'}"
  n_layers: 3
  activation: relu

decoder:
  _target_: model.CMDecoder
  input_dim: ${SCM.n_variables}
  hidden_dim: 64
  n_layers: 3
  activation: relu
  graph: ${SCM}


callbacks:
  early_stopping:
    _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: val_loss
    patience: 1000
    mode: min
    verbose: True
